services:
  server:
    build: ./server
    container_name: conundrum-server
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=production

  client:
    build:
      context: ./client
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
        REACT_APP_SUPABASE_URL: ${REACT_APP_SUPABASE_URL}
        REACT_APP_SUPABASE_ANON_KEY: ${REACT_APP_SUPABASE_ANON_KEY}
    container_name: conundrum-client
    ports:
      - "80:80"
    depends_on:
      - server
    env_file:
      - ./.env
